<?php require_once('header.php'); ?> 
<div class="grid_3">
    <div class="container">
    <div class="breadcrumb1">
       <ul>
          <a href="index.php"><i class="fa fa-home home_1"></i></a>
          <span class="divider">&nbsp;|&nbsp;</span>
          <li class="current-page">Privacy Policy</li>
       </ul>
    </div>
     <div class="terms_1">
          <p>NeoVivah are committed to respecting your online privacy and recognize the need for appropriate protection and management of any personally identifiable information you share with us. This Privacy Policy describes how NeoVivah collects, uses, discloses and transfers personal information of users through its websites, including through www.neovivah.com, This policy applies to those who visit the Platform, or whose information NeoVivah otherwise receives in connection with its services such as contact information of individuals associated with us hereinafter collectively referred to as Users. For the purposes of the Privacy Policy, “You" or “Your” shall mean the person who is accessing the Platform.</p>
          <p>“Personal information collected by NeoVivah” - Means any information relating to an identified or identifiable natural person including common identifiers such as a name, an identification number, location data, an online identifier or one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person and any other information that is so categorized by applicable laws. NeoVivah collect information about you and/or your usage to provide better services & offerings. The Personal Information that NeoVivah collect, and how NeoVivah collect it, depends upon how you interact with NeoVivah collect the following categories of Personal Information.</p>
          <p>NeoVivah collect your Personal Information such as name, email address, date of birth, mobile number, mother tongue, password, country, state/nationality, gender, current location, city, pin code, marital status, height, occupation, income etc. When you complete your profile, you can share with us additional information, such as details on your personality, family details, contact address and other details about you, as well as content such as photos. To add certain content, like pictures, you may allow us to access your camera or photo album. Some of the information you choose to provide us may be considered “special” or “sensitive” in certain jurisdictions, for example your ethnic origins, religious beliefs, sub caste, physical and mental conditions. By choosing to provide this information, you consent to our processing of the information. when the you sign up as a member or you set up an alert on the Platform, NeoVivah reach out to you as per your settings Information that one would usually include in a matrimonial profile, including name, contact details such as e-mail address and mobile number, date of birth, status etc. when you register on the Platform. Information about the services that you use and how you use them, including log information and location information, when you are a user of the services through the Platform. NeoVivah collect your Personal Information such as name, age, contact details, preferences, etc. through surveys and forms, when you choose to participate in these surveys etc. NeoVivah can collect your documents on age, address, income etc. for verification purposes to provide additional credibility to your profile. When you communicate with NeoVivah or use the Platform to communicate with other members (including advertisers, Users (such as partners), NeoVivah collect information about your communication and any information you choose to provide. When you visit the Platform, NeoVivah use cookies to automatically collect, store and use technical information about your system and interaction with our Platform. When you use a device to access the Platform, NeoVivah collect technical or other related information from the device as well as the device location. To the extent permitted by law, NeoVivah may record and monitor your communications with us to ensure compliance with our legal and regulatory obligations and our internal policies. When you use your social media account information to access the Platform, or otherwise connect your social media account with the services of the Platform, you consent to our collection, storage, and use, in accordance with this Privacy Policy, of the information that you make available to us through the social media interface. Please see your social media provider's privacy policy and help centre for more information about how they share information when you choose to connect your account.</p>
          <p>How NeoVivah may use your Personal Information-  Use your personal data in a fair and reasonable manner, and where NeoVivah have a lawful reason to do so. Our use of your personal data depends on the purpose for which you interact with us. NeoVivah process your Personal Information for the following purposes:</p>
          <p>Protecting our Users and providing you with customer support;</p>
          <p>Our automated systems analyse your content to provide you customised search results and recommendations.</p>
          <p>Send alerts and emails such as match alert mails, membership mails, visitor alert mails, new matches mails, contact alert mails, photo request mails, service mails, promotional mails, SMS alerts and call alerts(s) to you ( To unsubscribe, please text us at neovivah@gmail.com  subject text unsubscribe)</p>
          <p>NeoVivah also process your chats with other users of the Platform, for purposes such as fulfillment of legal obligations, monitoring for offensive or menacing content etc.</p>
          <p>Conducting market research and surveys with the aim of improving our products and services.Sending you information about our products and services for marketing purposes and promotions;Preventing, detecting, investigating and taking action against crimes (including but not limited to fraud and other financial crimes), any other illegal activities, suspected fraud, or violations of the Platform’s Terms of Use in any jurisdiction To the extent required for identity verification and due diligence checks if so undertaken.</p>
          <p>Cookies and Other Tracking Technologies- Some of our web pages utilize "cookies" and other tracking technologies. A "cookie" is a small text file that may be used, for example, to collect information about web-site activity. Some cookies and other technologies may serve to recall Personal Information previously indicated by a user. Most browsers allow you to control cookies, including whether or not to accept them and how to remove them. You may set most browsers to notify you if you receive a cookie, or you may choose to block cookies with your browser, but please note that if you choose to erase or block your cookies, you will need to re-enter your original user ID and password to gain access to certain parts of the Platform. Tracking technologies may record information such as Internet domain and host names; Internet protocol (IP) addresses; browser software and operating system types; clickstream patterns; and dates and times that our site is accessed. Our use of cookies and other tracking technologies allows us to improve our Platform and the overall website experience. NeoVivah also analyse information that does not contain Personal Information for trends and statistics.</p>
          <p>The Basis/ Grounds which NeoVivah rely on for collection and processing of your Personal Information:</p>
          <p>Your Personal Information is collected and processed by NeoVivah based on the following legal grounds depending upon the nature of Personal Information and the purposes for which it is processed.</p>
          <p>Consent- NeoVivah relies on your consent in order to process your Personal Information in certain situations. If NeoVivah requires your consent to collect and process certain Personal Information, as per the requirements under the applicable data protection laws, your consent is sought at the time of collection of your Personal Information and such processing will only be performed where consent is secured.</p>
          <p>Compliance with a legal obligation:- Your Personal Information may be processed by NeoVivah, to the extent that such processing is necessary to allow NeoVivah to comply with a legal obligation. An example of this would be if NeoVivah is required to disclose your Personal Information to respond to a court order or if NeoVivah is required to retain specific records for a fixed period to comply with requirement under any applicable law.</p>
          <p>Information Sharing and Disclosure- Third Party Services: Third parties provide certain services available on the Platform on its behalf. Platform may provide information, including Personal Information and special/ sensitive personal information, that the Platform collects from its users to third-party service providers to help us deliver programs, products, information, and services. Service providers are also an important means by which the Platform maintains its services and mailing lists. NeoVivah restrict access to your Personal Information to employees who NeoVivah believe reasonably need to know/or that information to fulfil their functions to provide, operate, develop, or improve our products or services. NeoVivah does not disclose, transfer or share your Personal Information with others.</p>
          <p>Third parties including enforcement, regulatory and judicial authorities, if NeoVivah determine that disclosure of your Personal Information is required to (A) Respond to subpoenas, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims; or (B) Investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Platform’s Terms & Conditions or as otherwise required by law;
          </p>
          <p>Third party service providers and marketing partners that NeoVivah engages to (A) Provide services over the Platform on NeoVivah’s behalf; (B) Maintain the Platform and mailing lists; or(C) communicate with you on NeoVivah’s behalf about offers relating to its products and/or services. NeoVivah will take reasonable steps to ensure that these third-party service providers are obligated to protect your Personal Information and are also subject to appropriate confidentiality / non-disclosure obligations.</p>
          <p>Third party advertisers to display advertisements to you when you visit the Platform. The third-party advertisers include financial service providers such as banks, insurance agents, stock brokers and mortgage lenders and non-financial companies such as stores, airlines, and software companies. These companies may use information about you and your visits to this Platform and other web sites to provide advertisements on this Platform.</p>
          <p>NeoVivah does not provide any Personal Information to the advertiser when you interact with or view a targeted advertisement. However, if you interact with or view an advertisement, the advertiser may make certain assumptions and, in the process, learn certain Personal Information about you. For instance, if you view and click an advertisement that is targeted towards women in the age group 18- 24 from a specific geographic area, the advertiser may assume that you meet the relevant criteria.</p>
          <p>NeoVivah does not intend to transfer Personal Information without your consent to third parties who are not bound to act on NeoVivah's behalf unless such transfer is legally required.</p>
          <p>Third Party Content- Please be aware that the Platform sometimes contains links to other sites that are not governed by this Privacy Policy. Users may be directed to third-party sites for more information, such as advertisers, blogs, content sponsorships, vendor services, social networks, etc. NeoVivah makes no representations or warranties regarding how your information is stored or used on third-party servers. NeoVivah recommend that you review the applicable privacy statements and policies of each third-party site linked from the Platform to determine their use of your personal information.</p>
          <p>Children- To use the Platform, you agree that you must be the minimum age for these purposes shall be eighteen (18), that you must be older for NeoVivah to be able to lawfully provide the services over the Platform to you then that older age shall apply as the applicable minimum age.</p>
          <p>Retention of Personal Information- Your Personal Information will not be retained by NeoVivah any longer than it is necessary for the purposes for which the Personal Information is processed and/or in accordance with legal, regulatory, contractual 1 or statutory obligations as applicable. At the expiry of such periods, your Personal Information will be deleted or archived in compliance with applicable laws</p>
          <p>Controlling your personal information- You have the right to invoke your rights which are available to data principals or data subjects as per applicable laws and regulations in relation to your Personal Information which is being processed by NeoVivah. </p>
          <p>NeoVivah provides you the ability to keep your Personal Information accurate and up-to-date. If at any time you would like to (A) rectify, update or correct your Personal Information; (B) obtain confirmation on whether or not your Personal Information is processed by it; (C) access your Personal Information or exercise your right to data portability; or (D) exercise your right to restrict the continuing disclosure of your Personal Information to any third party by NeoVivah in certain circumstances, you are requested to contact us using the contact details mentions below. NeoVivah will require you to provide a valid proof of your identity, in order to ensure that your rights are respected.</p>
          <p>For the exercise of certain rights, you may be required to approach the relevant authority / designated officer as per the provisions of the applicable data protection laws. NeoVivah may in accordance with the provisions of applicable data protection laws, charge a fee for fulfilling your request, in particular in case of excessive or manifestly unfounded request. Further you acknowledge that the abovementioned rights are not absolute and are subject to limitations as per the applicable data protection laws.</p>
          <p>Confidentiality and Security- The security and confidentiality of your Personal Information is important to us and NeoVivah has invested significant resources to protect the safekeeping and confidentiality of your personal data. When using external service providers acting as processors, NeoVivah require that they adhere to the same standards as NeoVivah does. Regardless of where your Personal Information is transferred or stored, NeoVivah take all steps reasonably necessary to ensure that personal data is kept secure. NeoVivah seek to ensure compliance with the requirements of the Information Technology Act, 2000 and Rules made there under to ensure the protection and preservation of your privacy. By accepting the terms of this Privacy Policy, you agree that the standards and practices being implemented by NeoVivah, are reasonable and sufficient for the protection of your Personal Information.</p>
          <p>Social media- NeoVivah operates channels, pages and accounts on some social media sites to inform, assist and engage with customers. NeoVivah monitors and records comments and posts made on these channels about itself in order to improve its products and services. Please note that you must not communicate the following information to NeoVivah through such social media sites. sensitive personal data including (i) special categories of personal data meaning any information revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation and (ii) other sensitive personal data such as criminal convictions and offences and national identification number. Excessive, inappropriate, offensive or defamatory content. NeoVivah is not responsible for any information posted on those sites other than the information posted by its employees on its behalf. NeoVivah is only responsible for its own use of the Personal Information received through such sites.</p>
          <p>neovivah.com is committed to provide you with a safe & secure platform in which you search and find your partner. We help our users discover the best matches but it is in the interests of a user to use their best judgment to assess another person’s genuineness and interest in marriage.</p>
          <p>Despite all we do to make the platform secure, we advise some precautions while using our sites:</p>
          <p>If a user appears to have entered false, incorrect information about their education, profession, income, family etc., mark such profiles as ‘Report Abuse’ and refrain from contacting that user.</p>
          <p>If a user asks for personal favors like transportation of goods, deposit of funds on their behalf, lend them some money etc., immediately cease any communication with the user and do as advised above.</p>
          <p>Be cautious of fake or copy sites which may look similar but are actually owned by people who may have malicious intent. Many sites have a similar appearance as neovivah.com but they are not in any way related or affiliated to neovivah.com. Please check the URL of the site (it should be www.neovivah.com) that you are visiting.</p>
          <p>Representatives from these fake sites may reach out to you to get membership fee or for registering your profiles. Exercise caution and alert our customer service if and when this happens.</p>
          <p>Beware of people who pretend to call from the NeoVivah team asking for your user id’s to login to your account. Please note that NeoVivah never asks you for user password information either on phone or in person.</p>
          <p>Never share your financial details like bank account number, online banking credentials, credit card details etc. and be wary of those who ask for money from you. Use sound judgement and do not take any decision in a hurry.</p>
          <p>Meet with prospective partners you find on the platform in a safe place and inform your family or friends of the meeting.</p>
          <p>Do a thorough background research about the person before any commitments are made.</p>
          <p>neovivah.com is merely a preliminary medium of contact and exchange of information. Users are strongly advised to conduct an independent check/due diligence prior to proceeding with any decisions based on the content of the profile. The onus of verifying the authenticity of the information displayed on a profile lies on the user.</p>
          <p>Changes to this Privacy Policy- NeoVivah reserves the right to update, change or modify this Privacy Policy at any time. The Privacy Policy shall come to effect from the date of publication of such update, change or modification</p>
          <p>Disclaimer- NeoVivah does not store any account related information or any credit / debit card details. NeoVivah shall not be liable for any loss or damage sustained by Users as a result of any disclosure (inadvertent or otherwise) of any information concerning the User's account, credit cards or debit cards in the course of any oline transactions or payments made for any products and/or services offered through the Platform. In case any Personal Information is shared by you with NeoVivah, which is not requested by NeoVivah during registration, (whether mandatorily or optionally), NeoVivah will not be liable for any information security breach or disclosure in relation to such information.</p>
          <p>If you have any questions regarding this Privacy Policy or the protection of your Personal Information, In case you have any complaints and/or grievances in relation to the processing of your Personal Information you can send your complaints via e-mail to our grievance officer:</p>
          <p>NeoVivah</p>
          <p>Ghaziabad</p>
          <p>Contact us through Email</p>
          <p>neovivah@gmail.com</p>
       </div>
     </div>
  </div>
  <?php require_once('footer.php'); ?>