<?php require_once('header.php'); ?> 
<div class="grid_3">
    <div class="container">
        <div class="breadcrumb1">
            <ul>
        		<a href="index.php"><i class="fa fa-home home_1"></i></a>
        		<span class="divider">&nbsp;|&nbsp;</span>
        		<li class="current-page">Terms and Conditions</li>
     		</ul>
    	</div>
    	<div class="terms_1">
    		<p>NeoVivah.com Licensed for Accessing the Site (including all associated media and online or electronic documentation) are owned and operated by NeoVivah. The Site and Application are hereinafter collectively referred to as “Platform”.</p>
            <p>NeoVivah makes available its services and products to you, through the Platform on the condition that you abide by these Terms and Conditions, as updated from time to time. If you do not accept the Terms and Conditions or you do not meet or comply with their provisions, you should not use or access the Platform and/or avail of the services or products via the Platform.</p>
			<p>The Platform is an intermediary as defined under sub-clause (w) of Section 2 of the Information Technology Act, 2000. Visitors to the Platform are granted a nonexclusive, limited license to use and access the content and services offered in accordance with these Terms and Conditions (the "License").</p>
			<p>A Visitor to the platform, whether or not he/she has made any payment for availing access and/or services on the Platform, including the general browsers of the Platform, whether registered or not, are hereinafter referred to as “User/Users”.</p>
			<p>BY THE POSITIVE ACTS OF A USER ACCESSING THE PLATFORM, THE USER AGREES TO BE BOUND BY THE TERMS AND CONDITIONS SET BELOW (“Terms”). IF A USER DOES NOT AGREE WITH ANY OF THESE TERMS AND CONDITIONS, HE/SHE SHOULD NOT ACCESS OR USE THE PLATFORM.</p>
			<p>The Platform is intended only to serve as a preliminary medium of contact and information for Users who have a bona fide intention to enter into a matrimonial alliance (“Purpose”). The Platform does not purport to be a marriage or business bureau or a dating /contact website.</p>
			<p>NeoVivah presumes that every User who logs on to the Platform has a bona fide intention to get married / enter into a matrimonial alliance and not otherwise. NeoVivah under no circumstances shall be responsible for any loss or damage resulting from anyone's use of the Platform or the services offered on the Platform and / or any content posted on the Platform or transmitted to Users. The exchange of matrimonial profile(s) through or by the Platform should not in any way be construed as a matrimonial offer and/or recommendation by NeoVivah.</p>
			<p>NeoVivah shall not be responsible for any loss or damage to any individual arising in/out of, or subsequent to, matrimonial relations established pursuant to use of the service provided by NeoVivah.</p>
			<p>NeoVivah collects information / data including, without limitation, e-mail id, address, first name, last name, telephone/mobile number, date of birth, age, gender, ethnic/cultural background, appearance, religion, occupation, preferences, life style information, general geographical location (“User Data”) from Users in order to enable them to create their profiles on the Platform. Apart from this, certain other health related information, including physical and mental disabilities are also collected. The User Data so collected is entered in a program especially devised for matching profiles and to provide matches for Users based on their pre-selected partner preferences criteria. User Data is displayed only after taking prior consent of Users. NeoVivah does not collect financial information of Users such as credit card/debit card numbers/bank accounts numbers etc. NeoVivah shall not be able to provide access to the Platform and/or create profiles of Users if the requisite User Data is not provided by the Users. User hereby consents to usage of his/her User Data to be displayed to other Users on the Platform.</p>
			<p>Users hereby give us permission to use the information about their activities and actions that they have taken on the Platform in connection with ads, offers and other sponsored content that NeoVivah displays on the Platform, without charging any fees to the Users. NeoVivah uses data and information about Users to make relevant suggestions and recommendation to its Users.</p>
			<p>The User Data is uploaded by the Users themselves or through any of the NeoVivah offline centers displayed on the Platform. NeoVivah may, at its sole discretion, include all or any portion of the listing intimated by a User for display on the Platform in any other media including the matrimonial sections of other platforms including but not limited to print media, community associations, websites, television shows, DTH/IPTV Services, mobile wap sites etc. at no extra costs to the Users and NeoVivah shall not be held liable for usage/publicity of such information / data.</p>
			<p>Users undertake not to duplicate, modify and distribute material on the Platform unless specifically authorized by the NeoVivah in writing. Users undertake not to establish any deep link or other connection to any specific page of the Platform without obtaining prior written consent of NeoVivah.</p>
			<p>Users undertake to use the Platform for their personal purposes. Using content from the Platform for creating derivative works with a commercial motive without prior written consent from NeoVivah is strictly prohibited.</p>
			<p>NeoVivah takes measures including technological means on the Platform to exclude robots, scripts, programs etc. from crawling or scraping content on the Platform. Users undertake not to circumvent these methods.</p>
			<p>Any advice, counseling, recommendations or information provided on the Platform including information of Users may not be necessarily correct, true or reliable, and that any reliance placed thereon and any action taken on the basis thereof shall be entirely / solely at the risk of the concerned User. Users hereby agree that access to the content available on the Platform is provided by NeoVivah to Users on an ‘AS-IS’ and ‘AS-AVAILABLE’ basis. Users wishing to use the information so provided are advised to conduct their own due diligence, in respect of the content on the Platform, at their own initiative, cost and effort. NeoVivah does not advise / recommend a User to establish any contact / interaction with other Users or any based on the data / information as furnished in such User’s profile / photograph etc. and the User opting to build contact or interact shall do it solely at his / her own risk. NeoVivah cannot be held responsible or liable, in any manner whatsoever, in respect of any reliance placed on any information displayed / placed on the Platform, since the same purports merely to act as indicators of the general scenario in the related behalf.</p>
			<p>NeoVivah does not authenticate, vet, screen, endorse or investigate any information or assertion comprised in the matrimonial listings, or any other content on the Platform, nor does it in any manner whatsoever certify or attest the same to be correct or true. It does not endorse matches and profiles in any manner, but an implied presumption is cast on the Users that the information(s) furnished are exclusively / solely to carve out / frame a suitable profile for the purpose of matrimonial alliance based on the partner preferences criteria set by the Users. All due diligence, effort and initiatives must be exercised by those wishing to use any information found on the Platform, and should take adequate precautions with the full and complete knowledge that all information contained in the matrimonial listings have been placed there directly by Users of the Platform without any prior intimation, consent or verification of or by NeoVivah.</p>
			<p>Users of the Platform are prohibited from uploading, posting, transmitting, updating or sharing any information that:</p>
			<p>1. belongs to another person and to which the user does not have any right to;</p>
			<p>2. is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; harm minors in any way;</p>
			<p>3. infringes any patent, trademark, copyright or other proprietary rights;</p>
			<p>4. violates any law for the time being in force;</p>
			<p>5. deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; impersonate another person;</p>
			<p>6. contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of the Platform ; threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</p>
			<p>NeoVivah may, without notice in its sole discretion, and at any time, terminate or restrict a User’s usage or access to the Platform (or any part thereof) and/or take down any content uploaded by a User for any reason, including, without limitation, that NeoVivah based on its judgement and perception believes the a User has violated or acted inconsistently with the letter or spirit of these Terms.</p>
			<p>NeoVivah is an online service provider for Users to create their own/unique profiles envisaging certain personal (optional) information(s) and User Data are to be displayed on the Platform, which information is used by Users for the Purpose. NeoVivah does not share User Data with other Users or third parties with the prior consent of the User. Although NeoVivah shall take all reasonable precautions, NeoVivah shall not be responsible in case such User Data so displayed on the Platform being unauthorisedly copied / printed / published / forged / superimposed / manipulated etc. or misused by any User. Users shall indemnify NeoVivah from all kind of losses / damages which NeoVivah may suffer from any activities carried out by them through improper use of the Platform/service provided by NeoVivah.</p>
			<p>By listing a matrimonial profile, or a business or personal listing or a link, or any content or listing, on the Platform, the concerned User making or posting such listing, and the person or persons responsible for such posting or listing, shall be deemed to have agreed to hold NeoVivah harmless and protected against any suit or complaint, civil, pecuniary or criminal, and against any claims or damages (including, without limitation, interests, fines and penalties) which may be brought against or levied on NeoVivah on account of any matter arising out of, or relating to, such posting / listing or response received from such posting/listing.</p>
			<p>Whilst using the Platform an obligation is cast upon Users to only provide true and correct information and in the case of creating a profile Users undertake at all times to keep the information up to date. NeoVivah does not represent or endorse the accuracy or reliability of any member / visitor profile, advice, opinion, statement or other information displayed / uploaded through the service by NeoVivah or any of its owners, staff or agents are not responsible under any circumstances for any action/display whether direct or indirect, which occurs as a result of online display of information in the nature of illicit material / material that may be offensive to visitors / members or is patently offensive to the on-line community or any material which may promote racism, bigotry, hatred or physical/mental harm of any kind to any group or individual or transmit any chain letters or junk mail or unsolicited mass mailing or spamming or obscene material to other users / members. NeoVivah does not monitor the conduct of Users and therefore NeoVivah does not take the responsibility of any conduct by Users who may avail / obtain / use / exploit the online service provided by neovivah.com in order to harass, abuse or harm another Users or use the said online service to promote / advertise / solicit anything without their prior consent or an act in any manner which may threaten the safety of other Users.</p>
			<p>NeoVivah reserves the right to remove / delete any content / message / photo(s) / profile or cancel the registration / membership of a User either upon a complaint received from another User or upon discovery of the same on its own or based on its sole judgment and perception and it shall without notice stop providing the service entitled to a User and forfeit all other incidental service(s) with immediate effect along with the fee/tenure of registration as well as take appropriate legal action against such User. By listing a profile on the Platform, it is deemed that the said User has an intention to get married and in case it appears to NeoVivah that at the time of listing the profile or subsequently such User had no intention to enter into a matrimonial alliance or has changed his/her intention, then NeoVivah shall reserve the right to remove / delete such profile from the Platform and initiate prosecution under the law or take such steps as may be advised from time to time. By using the Platform, it is deemed that the User agrees not to post any content or views that may be considered threatening, abusive, vulgar, obscene or otherwise objectionable or act illegally or otherwise harass another user; put wrong or misleading information in any of the details of his/her own profile; impersonate another or use the site for any commercial purposes; or interfere with or disrupt the operation of this site, or disobey any reasonable requirements, procedures or policies imposed by NeoVivah from time to time.</p>
			<p>Nothing comprised in the contents of the Platform is intended or meant to induce or persuade or convince or invite any person whatsoever to perform any action or do any such thing, or not to perform or do, where such performance or doing, or non-performance or not doing, constitute any contravention of any law or regulation in force for the time being to which such person or action may be governed.</p>
			<p>NeoVivah shall not be held responsible for any interactions/ passing of information(s) etc. between any User via e-mail, chat or any other medium with another User and NeoVivah has no obligation, to monitor any such disputes arising between the Users and NeoVivah shall not be party to such dispute/litigation etc.</p>
			<p>NeoVivah reserves the absolute right to modify or amend or delete, in any manner as it deems fit, any content of any matrimonial listing placed on the Platform in order to ensure compliance with the rules of such placement (which may include, without limitation, the efforts and initiatives by NeoVivah to maximize response to matrimonial listings), prima facie accuracy and the prevailing laws in force for the time being, especially those relating to prohibition of any indecent, unlawful or obscene content. NeoVivah reserves the absolute right to delete any profile if it finds that the same person has created multiple profiles on the Platform. Even if different profiles have been created with the same contact details, NeoVivah will reserve the absolute right to delete all such profiles. If any member refuses to give consent to a physical address verification that NeoVivah has requested then NeoVivah will have the absolute right to either put a "Not Verified" stamp on the profile or to delete the profile.</p>
			<p>Websites to which links are given on the Platform and the contents thereof are the sole responsibility of the promoters of such websites and NeoVivah does not, in any manner whatsoever, recommend, authenticate, endorse, verify or certify these websites or any contents or links there. NeoVivah does not take any responsibility for the privacy practice adopted by such other websites and therefore NeoVivah recommends Users to read the privacy statement of each and every website that they visits. NeoVivah also does not take any responsibility or endorse the authenticity of the other online services displayed on the Platform which may offer various services like a lucky draw, win a free trip, win free tickets, astrology, palmistry, numerology etc. User of the Platform shall at its sole risk and responsibility click and surf on to such other website(s) / links which is/are being displayed on the Platform. Users shall always bear in mind that at a single stroke/click of the mouse on such links/website, it gets connected through the Transmission Control Protocol (TCP) / Internet Protocol (IP) network of the said Users and not through the IP of the Platform. NeoVivah also does not suggest/encourage Users to furnish personal information and specially the Profile ID / User Name of the User on the Platform to such or any other website(s).</p>
			<p>NeoVivah reserves the right to tie up with partners in future to come up with various other online services. However, NeoVivah shall never share the information / data collected from Users with such other partners without taking prior consent / permission from such Users. NeoVivah in such circumstances suggests that Users peruse the privacy policy of such partners before giving their consent or before furnishing personal identifiable information with such other website(s). NeoVivah is not privy to the privacy practice adopted by its partners and does not take the responsibility in respect of the privacy policy adopted / to be adopted by such partners. NeoVivah also reserves the right to use / share the information / data collected from Users with its partners if a User has already made public the information / data to Users of the Platform.</p>
			<p>NeoVivah hereby specifically disclaims any liabilities or warranties or guarantees, express, specific or implied, which may be attributable, in any manner whatsoever, to the existence, promotion, canvassing, contents, links, information or discontinuance of the Platform. No claims for damages, restitution, loss-of-profits, or any other pecuniary, civil or criminal plaints, which may be said to arise out, or on account, of any matter contained or related to the Platform, shall lie or be deemed to be sustainable against NeoVivah.</p>
			<p>NeoVivah assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of User communications. NeoVivah is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of e-mail or players on account of technical problems or traffic congestion on the internet or at any website or combination thereof, including injury or damage to Users or to any other person's computer related to or resulting from participating or downloading materials /information from the Platform.</p>
			<p>Users who visit the Platform are classified by NeoVivah as Users with incomplete or complete profiles. Both these types could further be free members or paid members. NeoVivah reserves the absolute right to modify, amend, change, curtail or expand any privileges, rights, benefits, liabilities or responsibilities of all types of paid Users or free Users as it deems fit and these will be instantly applicable to all past, present and future Users. NeoVivah allows free Users certain benefits /privileges like initiating free contact via "Express Interest" functionality, like viewing contact details of paid Users under certain conditions etc. The quantum of these benefits and even the benefits in totality will be at the sole discretion of NeoVivah will determine at its own discretion how many benefits it offers to every free User. NeoVivah will simultaneously offer different levels of benefits to different free Users Benefit restriction to free Users will be done via multiple means including restricting access, spam filters, quotas etc.</p>
			<p>Refund & Cancelation policy- Payments for the services offered on the Platform shall be on a 100% advance basis. The payment for service once subscribed by the User is refundable till next 48 hours for the payment user need to ask refund within next 48 hours. email at neovivah@gmail.com with requested detail payment reference no, NeoVivah Registered Id no, registered email & mobile no, user need to text subject “refund request” form his/her register email id only. NeoVivah committed to refund paid amount after the deduction of admin charge & user usage pack in said 48 hours which can be 20 to 35 % NeoVivah and it offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the User’s card/bank accounts. NeoVivah gives no guarantees of server uptime or applications working properly. All is on a best effort basis and NeoVivah’s liability for losses, damages and claims hereunder is limited to refund of amount only. NeoVivah undertakes no liability for free services. NeoVivah reserves its right to amend / alter or change all or any disclaimers or these Terms at any time without any prior notice.  All terms / disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them. The continued usage of the Platform by a User shall constitute deemed acceptance by the User of the amended Terms.</p>
			<p>The User is solely and exclusively responsible for maintaining confidentiality of the User password and User identification and all activities and transmission performed by the User through his/her user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and NeoVivah assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / offline. NeoVivah uses reasonable care as is necessary to ensure that all or any data / information does not fall in the wrong hands. The weak link in credit card transaction is securely storing the data once received; therefore NeoVivah does not store or keep credit card/debit card/bank account. For the purposes of ensuring the maximum security for the financial information of a user (such as credit card/debit card/internet banking data) all such online payment transactions are carried out directly on the secured platforms of payment gateways and not on the Platform.</p>
			<p>NeoVivah does not warrant that the Platform will be uninterrupted or error-free. NeoVivah provides the service on an "as is" basis. However, NeoVivah will take all reasonable steps to provide its users with error free, uninterrupted user experience. There may be delays, omissions, and interruptions in the availability of the Platform. Users acknowledge that use of the Platform is solely at their cost and risk. NeoVivah is not responsible for suspension of the services on the Platform, irrespective of the reason for such interruption / suspension. NeoVivah may discontinue or change the services on the Platform or its availability at any time, and the User is also free to stop availing the services on the Platform at any time.</p>
			<p>NeoVivah uses third party payment gateways on the Platform and failures in these gateways would be communicated to the users as it is. Extra currency/conversion charges/deductions/error issues from payment gateway shall not be the responsibility of NeoVivah.</p>
			<p>NeoVivah has complete rights in the Platform and the services provided thereunder. The Platform contains to the extent protected by applicable laws, copyrighted material, trademarks, and other proprietary information of its owners and its licensors. Except for that information which is in the public domain or for any other information/display for which permission have not been obtained from NeoVivah reserves the right to proceed/initiate appropriate steps under the prevailing law against infringement of the said proprietary rights for illegal copying, modifying, publishing, transmitting, distributing, performing, displaying, or selling of any such proprietary information.</p>
			<p>NeoVivah reserves the right to verify the authenticity of Content posted on the site.
			 NeoVivah if circumstances warrant may call for / ask any of its Users to provide documentary or other form of evidence supporting the information / User Data posted on the Platform and the User, without any protest shall produce such documentary / other evidence in support of such information and if the User fails to produce such information within a reasonable or stipulated time frame, NeoVivah may, in its sole discretion, terminate the profile/access to the Platform and forfeit the advance without a refund and take appropriate steps under the provisions of law. NeoVivah also reserves the right to investigate and take appropriate legal action without limitation at its sole discretion against any User who violates / misuses the online services and terminating the profile/access to the Platform of such violators without prior intimation who utilise the Platform in any manner which brings into disrepute or impairs the interests and functioning of Platform or the NeoVivah.</p>
			<p>NeoVivah also reserves the right to investigate and take appropriate legal action without limitation at its sole discretion against any User who violates / misuses the online services and terminating the profile/access to the Platform of such violators without prior intimation who utilise the Platform in any manner which brings into disrepute or impairs the interests and functioning of Platform or the NeoVivah.</p>
			<p>NeoVivah does not take the responsibility of any information posted by its Users on the Platform, any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights and in case NeoVivah receives/discovers any such infringement, the said User may be called for / asked to furnish / provide evidence / relevant information in support of such display like an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest or a description of the copyrighted work that may have been infringed or information or a written statement that the User under bona-fide faith belief that the disputed information does not lead to any authorized use or infringement of copyright etc, under the law or a statement that the User is liable to penalty of perjury in case any of the information/statement furnished is proved otherwise or a declaration that the information displayed/posted is accurate and the User is itself the copyright owner or authorized to act on the copyright owner's behalf.</p>
			<p>NeoVivah has no obligation to monitor the activities of its Users. However, NeoVivah has the right to monitor the Platform electronically from time to time and to disclose any information as necessary to satisfy any law, regulation or other governmental request, to operate the Platform properly, or to protect itself or its Users. NeoVivah also reserves the right to refuse to post or to remove any information or materials, in whole or in part, that, in its sole discretion, are unacceptable, undesirable, or violative of provision of law.</p>
			<p>The usage of this Platform and any disputes/issues arising out of it shall be subject to the applicable laws in force for the time being in the Uttar Pradesh irrespective of conflicting provisions of law and to the exclusive jurisdiction of courts located in Ghaziabad (Uttar Pradesh).</p>
			<p>* Subject to profile download & Express Interests limit "Once package limit over you may recharge your pack the discretion of the NeoVivah and download more profile".</p>
			<p>In case NeoVivah receives any incriminating evidence/complaint against any User from other Users of the Platform or if NeoVivah, through data available to it from its servers, suspects misbehavior on any User’s part, it reserves the right to impose restrictions on the User’s account which include but may not be confined to preventing the User under question from making multiple contacts and restricting the user to only contact members whose desired partner profile the User satisfies.</p>
			<p>NeoVivah guidelines prohibit members to give their name and/or contact details in any form - Email, Phone nos., Messenger Ids, Postal address etc in any fields other than the specific ones where the same information is asked. If any member who puts the above information in any field other than the one meant for that purpose then NeoVivah screening team will remove the same.</p>
			<p>Users of the Platform are consenting for receiving</p>
			<p>1) Membership Emails: Emails conveying the benefits of paid membership to Users. These are sent to the Email address mentioned by the Users in their profile.</p>
			<p>2) Important Notifications from the Platform – Messages/notifications are sent to Users to inform them of various alerts related to usage of the Platform. . These will be communicated to the Users by Email notifications etc. or on their Landline/Mobile from a non-140 number via SMS/MMS/VMS/USSD/IVR/Calls etc.</p>
			<p>3) Membership SMSes/Calls: SMSes or phone calls shall be sent conveying the benefits of paid membership to Users. Users will receive these calls or SMS on any of the phone numbers mentioned by Users on their profile, if they have subscribed to calls/ SMS in their alert manager settings.</p>
			<p>Promotional Mails - . Promotional emails are sent to members on their Email ids, if they have subscribed to promotional emails in their alert manager settings.</p>
			<p>Users who sign up for www.neovivah.com Exclusive services allow NeoVivah to find suitable candidate/prospects on their behalf as per their instructions via Telephone, SMS, profile action on www.neovivah.com Platform, face to face interaction or any other means/modes of communication.</p>
			<p>Creation of duplicate profile on www.neovivah.com is prohibited. In case the user has forgotten his password he can use the password retrieval option. Forgetting password, User ID, reaching contact limits or any other reason for creating a 2nd profile on www.neovivah.com is not allowed. NeoVivah reserves the right to delete/block this profile or restrict access of this profile to use the Platform. NeoVivah at its own discretion can decide to delete/block/restrict access of 2nd profile or the original profile or both profiles in all cases where duplicate profiles have been found.</p>
			<p>Use of certain features on the Platform is governed by rules. For example if your phone number is not verified then you cannot contact other members via "Express Interest" or even if the same is happening then that privilege can be blocked by NeoVivah at any time without giving any notice. Similarly If your phone number is not verified then even as a person who has availed a "Paid Service" you will still not be able to view phone/email/contact details of other members via any option on the Platform. For verifying your phone number, there are verification prompts across the Platform which guide you on how to verify your phone. If the same is not clear then it is the member's responsibility to call customer care of Platform from the number which he/she wishes to verify.</p>
			<p>Any paid memberships are non-transferable. Any membership which is purchased is being purchased for that individual and cannot be used for any other profile in his/her family/friends/acquaintances etc. If a profile is deleted for whatsoever reason then that persons membership lapses.</p>
			<p>Paid members can see Phone/Email of other members subject to the total limits on "Profile Download" as specified on the membership page for the pack they have purchased. When the Users profile download of any other member, they would be able to see one or more of the following details: Email, Mobile Number and Landline number. This is deemed as a Contact View and a count is deducted from the User’s "Profile Download" quota. However, The Platform does not guarantee that the User will be able to speak/correspond with the profile on the provided Mobile, Landline or Email ID.</p>
			<p>Any profile closed by the profile user can be reclosed.</p>
			<p>NeoVivah do housekeeping of profiles which are not logged in for a period of 12 months. NeoVivah remove all the data associated with the profile during housekeeping.</p>
			<p>Restriction / Prohibitions</p>
			<p>The following actions will inter alia constitute a misuse of the Platform and are strictly prohibited:</p>
			<p>Copying, extracting,  sharing, modifying, selling, storing, distributing, making derivate works from or otherwise exploiting any content, data, information, including profiles, curriculum vitae, photographs and/or graphics, available on the Platform and/or any services or products of the NeoVivah, in any manner or for any purpose which is not, consistent with the Purpose and/or in accordance with the Terms of Use.</p>
			<p>Users are expressly prohibited from using or exploiting the Platform and/or any content or data provided therein for:</p>
			<p>(1) any commercial purposes such as creating alternate databases, extending access to the Platform to third parties without prior written consent of NeoVivah; and/or</p>
			<p>(2) undertaking any business activity which is in competition with the business of the NeoVivah; and/or</p>
			<p>(3) for seeking fees in any name whatsoever; and/or</p>
			<p>(4) approaching candidates/jobseekers for any purposes other than for specific existing vacancies; and/or</p>
			<p>(5) Sharing access with persons who are not contracted with the NeoVivah.</p>
			<p>(6) Reselling the products/services offered by the NeoVivah.</p>
			<p>(7) (Using or attempting to use any automated program, software or system or any similar or equivalent process (including spiders, robots, crawlers etc.) to access, navigate, search, copy, monitor, download, scrape, crawl or otherwise extract in any manner, any data or content including but not limited to adding or downloading profiles, contact details, or send or redirect messages from the Platform;</p>
            <p>(8) Gaining or attempting to gain unauthorized access (inter alia by hacking, password “mining” or any other means) to:</p>
			<p>(9) any portion or feature of the Platform or any of the services or products offered on or through the Platform which are not intended for you</p>
			<p>(10) any server, website, program or computer systems of the NeoVivah or any other third parties and/or Users;</p>
			<p>(11) Modifying the services provided through the Platform or their appearance using any technology or overlay any additional offering on top of such services or simulate the Platform’s services or its functions in any manner whatsoever without explicit consent obtained in writing by approaching us at neovivah@gmail.com</p>
			<p>(12) Accessing the Platform through interfaces other than those expressly provided by NeoVivah;</p>
			<p>(13) Attempting to breach or breaching any security or authentication measures set up by the NeoVivah in relation to the Platform and/or attempting to probe, scan or test the vulnerability of the NeoVivah’s system or network;</p>
			<p>(14) Reverse engineering, decompiling, disassembling, deciphering or otherwise attempting to do any of the aforesaid or deriving the source code for the Site or Application or any related technology or any part thereof;</p>
			<p>(15) Circumventing or attempting to circumvent any technological protections used or employed by NeoVivah or by any third party in order to protect the content on the Platform and/or to exclude robots, spiders etc. from crawling and /or scraping content from the Platform.</p>
			<p>(16) Bypassing or Circumventing or trying to circumvent any service limits including but not limited to Search limits, Captcha limits and occurrences on different triggers</p>
			<p>(17) Interfering with or disrupting or attempting to interfere with or disrupt (including by using any device, software or routine), the use of the Platform or any computer networks connected to the Platform, by any other User;</p>
			<p>(18) Developing, using or attempting to use any automated program, scripts, robots, third party software or system or any similar or equivalent process (including spiders, robots, crawlers, browser plug-ins/extensions/add-ons, iframes on third party sites, mirroring, HTML parsers etc.) to access, navigate, search, copy, monitor, scrape, crawl or otherwise extract or modify  in any manner, any data or content from the Platform without explicit consent obtained in writing by approaching us at neovivah@gmail.com;</p>
			<p>(20) Impersonating any other person or entity, or making any misrepresentation as to your employment by or affiliation with any person or entity;</p>
			<p>(21) Forging headers or in any manner manipulating identifiers in order to disguise the origin of any user information;</p>
			<p>(22) Stalking, threatening, or in any manner harassing any other User;</p>
            <p>(23) Imposing an unreasonable or disproportionately large load on the Platform infrastructure;</p>
			<p>(24) Engaging in “framing,” “mirroring,” or otherwise simulating the appearance or function of the Platform (or any part thereof) and providing deeplinks into this Platform (or any part thereof) without prior permission of NeoVivah;</p>
			<p>(25) Spamming the Platform/NeoVivah or any other Users including by uploading, posting, emailing, SMS, transmitting or otherwise making available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail.</p>
			<p>(26) Using the Platform or the contact details of Users for transmitting marketing and promotional mailers/ Offensive messages/ messages or communications using any media that are unrelated to recruitment or sending unsolicited commercial communications with misleading subject lines in order to intentionally obfuscate the original message.</p>
			<p>(27) Hosting, modifying, uploading, posting, transmitting, publishing, or distributing any material or information that:</p>
			<p>a. Violates any applicable local, provincial, state, national or international law, statute, ordinance, rule or regulation for the time being in force;</p>
			<p>b. Belongs to another person and to which you have no right;</p>
			<p>c. Infringes, breaches or otherwise contravenes the rights of NeoVivah or any third party, including any copyright, trademark, patent, rights of privacy or publicity or any other proprietary rights;</p>
			<p>d. Contains computer viruses, or other computer code, files or programs designed to disrupt, destroy or interfere with or limit the functioning of the Platform, or any other computer system or resource;</p>
			<p>e. Is grossly harmful, harassing, invasive of another's privacy, hateful, disparaging, relating to or encouraging money laundering or gambling in any manner, any content which is or may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous, blasphemous, vulgar, pornographic, paedophilic, obscene, or racially, ethnically, or otherwise unlawful in any manner whatsoever;</p>
			<p>f. Which constitutes or encourages conduct that would constitute a criminal offence, give rise to other liability, or otherwise violate applicable law;</p>
			<p>g. That deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
			<p>h. That harms minors in any way;</p>
			<p>i. That threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting to any other nation.</p>
			<p>If you have any questions regarding this Terms & Condition or the protection of your Personal Information, In case you have any complaints and/or grievances in relation to the processing of your Personal Information you can send your complaints via e-mail to our grievance officer:</p>
			<p>NeoVivah</p>
			<p>Ghaziabad</p>

			<p>Contact us through Email</p>
			<p>neovivah@gmail.com</p>
    	</div>
   </div>
</div>
<?php require_once('footer.php'); ?>